// modals
export const SET_IS_OPEN_ADD_TASK_MODAL = 'SET_IS_OPEN_ADD_TASK_MODAL';
export const SET_IS_OPEN_CANCEL_ADD_TASK_MODAL = 'SET_IS_OPEN_CANCEL_ADD_TASK_MODAL';
export const SET_IS_OPEN_REMOVE_TASK_MODAL = 'SET_IS_OPEN_REMOVE_TASK_MODAL';
export const SET_IS_OPEN_TASK_MODAL = 'SET_IS_OPEN_TASK_MODAL';

// task
export const SET_TASK_TITLE = 'SET_TASK_TITLE';
export const SET_SAVE_TASK = 'SET_SAVE_TASK';
export const SET_SAVE_TASK_SUCCESS = 'SET_SAVE_TASK_SUCCESS';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK';

export const SET_REMOVED_TASK_ID = 'SET_REMOVED_TASK_ID';
export const SET_REMOVED = 'SET_REMOVED';


